{% set name = "django-rosetta" %}
{% set version = "0.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 96e88ec243f8ff3332b7f267a219cf464df3af0d49c7bb13a6f1e7eb7fada5dd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six >=1.2.0
    - django >=1.11
    - requests >=2.1.0
    - polib >=1.1.0

test:
  imports:
    - rosetta

about:
  home: https://pypi.org/project/django-rosetta
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Django application that eases the translation of Django projects

  description: |
    Rosetta is a Django application that eases the translation process of your Django projects.
    Because it doesn't export any models, Rosetta doesn't create any tables in your project's database. 
    Rosetta can be installed and uninstalled by simply adding and removing a single entry in your project's INSTALLED_APPS and a single line in your main urls.py file
    Note: As of version 0.7.13 django-rosetta requires Django 1.8 or later. As of version 0.9.0, django-rosetta requires Django 1.11 or later.

  doc_url: http://django-rosetta.readthedocs.org/
  dev_url: https://github.com/mbi/django-rosetta/

extra:
  recipe-maintainers:
    - kcemenike
